# -*- coding: utf-8 -*-

standalone_run="""Usage: %(program)s standalone-run <input_file>

Run ITM Probe with the full input graph supplied in input file. Output is
full report printed to stdout.

Arguments:

   <input_file>:  A file in JSON format with ITM Probe arguments. If the
                  file is omitted, use stdin.
"""

custom_image="""Usage: %(program)s custom-image [OPTIONS] <output_file> <layout_file>
<script_file> <ITM_file>...

Produce a color image using a Graphviz (neato) layout for the subgraph.
Colors are specified through the script.

Arguments:

   <output_file>:  The file where the image is saved
   <layout_file>:  The file containing the layout
   <script_file>:  The file containing the script
   <ITM_file>:     An SQLite database containing a previously saved ITM

Options:

   -c, --colormap=<colormap>
          The colormap to use
   -f, --format=<svg|jpeg|png>
          Image format
   -i, --mixed-color
          Produce color mixture image
"""

run="""Usage: %(program)s run <input_file> <output_file>

Run ITM Probe

Arguments:

   <input_file>:   A file in JSON format with ITM Probe arguments
   <output_file>:  An SQLite database where the results are output
"""

batch_run="""Usage: %(program)s batch-run <input_file>

Run several ITM Probe jobs in one batch.

Arguments:

   <input_file>:  A file in JSON format with ITM Probe batch arguments.
"""

report="""Usage: %(program)s report [OPTIONS] <ITM_file>

Print a report for an ITM

Arguments:

   <ITM_file>:  An SQLite database containing a previously saved ITM

Options:

   -f, --format=<txt|csv|tab>
                  Output format
   -P, --input-params
                  Show only the ITM's input parameters
   -S, --summary  Show only the summary table
   -N, --nodes    Show only the network nodes table
   -m, --max-rows=<integer>
                  Maximum number of rows (nodes) to show (default 40)
   -r, --order-by=<variable>
                  Ordering criterion (column) (default 'total_content')
   -p, --use-p-ratio
                  Use participation ratio to determine the number of rows
                  to retreive (still limited by --max-rows option)
                  (default true)
   -t, --cutoff=<real>
                  Retrieve only rows where the --order-by column values
                  are greater than specified value. This option is
                  superseded by the ---use-p-ratio option
"""

table="""Usage: %(program)s table [OPTIONS] <script_file> <ITM_file> ...

Print a table with values extracted from a collection of ITMs by a script

Arguments:

   <script_file>:  The file containing the script for the table
   <ITM_file>:     A SQLite database containing a previously saved ITM

Options:

   -f, --format=<txt|csv|tab>
           Output format
"""

image="""Usage: %(program)s image [OPTIONS] <output_file> <layout_file> <ITM_file>...

Produce a color image using a Graphviz (neato) layout for the subgraph.
Colors are specified using default scripts.

Arguments:

   <output_file>:  The file where the image is saved
   <layout_file>:  The file containing the layout
   <ITM_file>:     An SQLite database containing a previously saved ITM

Options:

   -c, --colormap=<colormap>
      The colormap to use
   -b, --bins-func=<log|lin|sqrt>
      Discretization function (logarithmic, linear or square root)
   -f, --format=<svg|jpeg|png>
      Image format
   -i, --mixed-color
      Produce color mixture image
   -m, --max-rows=<integer>
      Maximum number of rows (nodes) to show (default 40)
   -r, --order-by=<variable>
      Ordering criterion (column) (default 'total_content')
   -p, --use-p-ratio
      Use participation ratio to determine the number of rows to retreive
      (still limited by --max-rows option) (default true)
   -t, --cutoff=<real>
      Retrieve only rows where the --order-by column values are greater
      than specified value. This option is superseded by the
      --use-p-ratio option
   -a, --value-cols=<columns>
      A comma-separated list of columns to be retrieved as node values.
      For mixed color image (-i), the default are all 'datacols'
      corresponding to sources or sinks depending on the ITM mode. For
      single color image, the default is the column indicated by -r
      option.
"""

custom_layout="""Usage: %(program)s custom-layout [OPTIONS] <output_file> <script_file> <ITM_file>...

Produce a Graphviz (neato) layout for the subgraph generated by the
script.

Arguments:

   <output_file>:  The file where the layout is saved
   <script_file>:  The file containing the script
   <ITM_file>:     An SQLite database containing a previously saved ITM

Options:

   -x, --neato=<path_to_neato>
         The full path to neato executable
   -s, --seed=<seed>
         Random seed for neato
"""

weights="""Usage: %(program)s table [OPTIONS] <column> <ITM_file> ...

Print a tab-delimited file suitable for piping into SaddleSum for
enrichment analysis. Sources, sinks, excluded and unreachable nodes are
automatically excluded.

Arguments:

   <column>:    A column (SQL expression) giving values for each valid
                note.
   <ITM_file>:  A SQLite database containing a previously saved ITM
"""

layout="""Usage: %(program)s layout [OPTIONS] <output_file> <script_file> <ITM_file>...

Produce a Graphviz (neato) layout for the subgraph using default script.

Arguments:

   <output_file>:  The file where the layout is saved
   <ITM_file>:     An SQLite database containing a previously saved ITM

Options:

   -x, --neato=<path_to_neato>
      The full path to neato executable
   -s, --seed=<seed>
      Random seed for neato
   -m, --max-rows=<integer>
      Maximum number of rows (nodes) to show (default 40)
   -r, --order-by=<variable>
      Ordering criterion (column) (default 'total_content')
   -p, --use-p-ratio
      Use participation ratio to determine the number of rows to retreive
      (still limited by --max-rows option) (default true)
   -t, --cutoff=<real>
      Retrieve only rows where the --order-by column values are greater
      than specified value. This option is superseded by the
      ---use-p-ratio option
"""

__program__="""Usage: %(program)s COMMAND [OPTIONS] ARGS

Commands:

   run:             run ITM Probe model
   standalone-run:  run ITM Probe model and output full report
   batch-run:       run several ITM Probe jobs in one batch
   table:           print a table from ITMs using custom script
   report:          print default report tables from an ITM
   layout:          produce Graphviz layout from ITMs using default
                    script
   custom-layout:   produce Graphviz layout from ITMs using custom script
   image:           produce an image from a Graphviz layout using default
                    script
   custom-image:    produce an image from a Graphviz layout using custom
                    script
   weights:         produce weights that can be piped to SaddleSum for
                    enrichment analysis

Try `%(program)s COMMAND --help` for help on a specific command.
"""

